### ISSUE TITLE
Invalid link to reference paper

### ISSUE THREAD

**Issue by jondegenhardt** [glow-stack/dlms#1]
The link to the scala papers in the [file block comment](https://github.com/glow-stack/dlms/blob/master/src/lms.d#L17) does not appear to be valid.

A google search went here: [https://scala-lms.github.io/publications.html](https://scala-lms.github.io/publications.html), perhaps that's the correct link now?

Also, I followed the `dub` "Documentation" link that leads to Adam Ruppe's documentation generator for this project : [https://dlms.dpldocs.info/index.html](https://dlms.dpldocs.info/index.html). It's a good start. If you think it's close you might consider adding the link to it the repository README.

Good to see you back!

**Comment by DmitryOlshansky** [comment]
Yeah, it’s:
https://scala-lms.github.io/publications.html

The link might have been obsoleted by now. Will fix. Hope you are going to read it - not the easiest read but it’s mind-opening the moment you get it (at least for me).

And yes, README is at best a stub. A few finishing touches are in order.

> Good to see you back!

Well this time around I’m only here for my own enjoyment ;)  No std/druntime/compiler work for the time being. Too many good ideas to count... all of them I wanted to try for ages now.

**Comment by jondegenhardt** [comment]
I'll read it. Don't know that I'll get, but it'll be worth it if I do!
